name: CI
on:
  pull_request:
  workflow_dispatch:

concurrency:
  # auto-cancel any in-progress job *on the same branch*
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          python-version: '3.13'
          use-uv: false
        - os: ubuntu-latest
          python-version: '3.13'
          use-uv: true
          venv-loc: bin
        - os: windows-latest
          python-version: '3.12'
          use-uv: false
        - os: windows-latest
          python-version: '3.12'
          use-uv: true
          venv-loc: Scripts
        - os: windows-latest
          python-version: '3.13'
          use-uv: false
        - os: windows-latest
          python-version: '3.13'
          use-uv: true
          venv-loc: Scripts

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - if: ${{ ! matrix.use-uv }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}

    - if: matrix.use-uv
      uses: astral-sh/setup-uv@v3

    - name: Build (pip)
      if: ${{ ! matrix.use-uv }}
      run: |
        pip install -r test_requirements.txt

    - name: Build (uv)
      if: matrix.use-uv
      run: |
        uv venv --python=${{matrix.python-version}} --python-preference=only-managed
        uv pip install -r test_requirements.txt

    - if: ${{ ! matrix.use-uv }}
      run: pip list
    
    - if: matrix.use-uv
      run: uv pip list

    - name: Test (pip)
      if: ${{ ! matrix.use-uv }}
      shell: bash
      run: |
        pytest --color=yes -ra

    - name: Test (uv)
      if: ${{ matrix.use-uv }}
      shell: bash
      run: |
        source .venv/${{matrix.venv-loc}}/activate
        pytest --color=yes -ra
