name: CI
on:
  pull_request:
  workflow_dispatch:

concurrency:
  # auto-cancel any in-progress job *on the same branch*
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          python-version: '3.13'
        - os: windows-latest
          python-version: '3.12'
        - os: windows-latest
          python-version: '3.13'

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}

    - name: Build
      run: |
        pip install -r test_requirements.txt

    - run: pip list

    - name: Test
      shell: bash
      run: |
        pytest --color=yes -ra
